import { defineField, defineType } from "sanity";

export const caseStudyType = defineType({
  name: "caseStudy",
  title: "Case Study",
  type: "document",
  groups: [
    { name: "basics", title: "Basics" },
    { name: "proof", title: "Proof & Story" },
    { name: "delivery", title: "Build & Results" },
    { name: "media", title: "Media & Preview" },
  ],
  fields: [
    defineField({
      name: "name",
      title: "Project Name [Example: Three Circles]",
      type: "string",
      description: "Public project name shown on portfolio cards and slug pages.",
      group: "basics",
      validation: (rule) => rule.required().min(3),
    }),
    defineField({
      name: "slug",
      title: "Slug [Example: three-circles]",
      type: "slug",
      options: { source: "name", maxLength: 96 },
      description: "Portfolio URL key in lowercase with hyphens.",
      group: "basics",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "livePreviewUrl",
      title: "Live Site URL [Example: https://threecircles.com]",
      type: "url",
      description: "Real public website URL for this project.",
      group: "media",
    }),
    defineField({
      name: "embeddedPreviewUrl",
      title: "Embeddable Preview URL (Optional) [Example: https://demo.threecircles.com]",
      type: "url",
      description: "Use only when the site allows iframe embedding. Best for demos on domains you control.",
      group: "media",
    }),
    defineField({
      name: "industry",
      title: "Industry [Example: Interior Design]",
      type: "string",
      description: "Readable industry label shown on the portfolio card and slug page.",
      group: "basics",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "category",
      title: "Portfolio Category (Optional) [Example: Websites]",
      type: "reference",
      to: [{ type: "portfolioCategory" }],
      description: "Primary portfolio grouping used for portfolio filters.",
      group: "basics",
    }),
    defineField({
      name: "categorySlug",
      title: "Category Slug Fallback (Optional) [Example: websites]",
      type: "string",
      description: "Fallback filter key when no Portfolio Category reference is selected.",
      group: "basics",
    }),
    defineField({
      name: "servicePage",
      title: "Service Page (Optional) [Example: Websites]",
      type: "reference",
      to: [{ type: "servicePage" }],
      description: "Optional linked service document.",
      group: "basics",
    }),
    defineField({
      name: "serviceSlug",
      title: "Service Slug [Example: websites]",
      type: "string",
      description: "Fallback service key used in filters and route logic.",
      group: "basics",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "summary",
      title: "Summary [Example: A premium company website for an interior design brand focused on elegance and conversion.]",
      type: "text",
      rows: 3,
      description: "Short project overview used in cards and detail intro.",
      group: "proof",
      validation: (rule) => rule.required().min(20),
    }),
    defineField({
      name: "metric",
      title: "Primary Metric [Example: +37% more qualified inquiries]",
      type: "string",
      description: "Headline proof point shown on portfolio cards and hero.",
      group: "proof",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "accent",
      title: "Accent Gradient [Example: from-stone-500 to-amber-700]",
      type: "string",
      initialValue: "from-teal-500 to-emerald-500",
      description: "Tailwind gradient classes used as visual accent.",
      group: "media",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "published",
      title: "Published",
      type: "boolean",
      initialValue: true,
      description: "Turn off to hide this case study publicly.",
      group: "basics",
    }),
    defineField({
      name: "featuredRank",
      title: "Featured Rank [Example: 12]",
      type: "number",
      initialValue: 999,
      description: "Lower numbers appear earlier in CMS-driven lists.",
      group: "basics",
    }),
    defineField({
      name: "heroImage",
      title: "Hero Image [Example: upload the real homepage or branded hero screenshot]",
      type: "image",
      options: { hotspot: true },
      description: "Main visual used on cards and the case study hero when no embed preview is available.",
      group: "media",
      fields: [
        defineField({ name: "alt", title: "Alt Text [Example: Homepage view of the Three Circles interior design website]", type: "string" }),
      ],
    }),
    defineField({
      name: "heroImageAlt",
      title: "Hero Image Alt Fallback [Example: Premium interior design company website homepage]",
      type: "string",
      group: "media",
    }),
    defineField({
      name: "client",
      title: "Client [Example: Three Circles]",
      type: "string",
      group: "proof",
    }),
    defineField({
      name: "year",
      title: "Year [Example: 2026]",
      type: "string",
      group: "proof",
    }),
    defineField({
      name: "duration",
      title: "Duration [Example: 4 weeks]",
      type: "string",
      group: "proof",
    }),
    defineField({
      name: "team",
      title: "Team [Example: Strategy, Design, Frontend, CMS]",
      type: "string",
      group: "proof",
    }),
    defineField({
      name: "challenge",
      title: "Challenge [Example: why the old site or system was not working]",
      type: "array",
      of: [{ type: "string" }],
      description: "One challenge point per line.",
      group: "proof",
    }),
    defineField({
      name: "strategy",
      title: "Strategy [Example: what decisions or changes solved the problem]",
      type: "array",
      of: [{ type: "string" }],
      description: "One strategic decision per line.",
      group: "proof",
    }),
    defineField({
      name: "build",
      title: "Build Highlights [Example: Platform = Next.js + Sanity]",
      type: "array",
      description: "Short key-value implementation notes.",
      group: "delivery",
      of: [
        {
          type: "object",
          fields: [
            defineField({ name: "label", title: "Label [Example: Platform]", type: "string", validation: (rule) => rule.required() }),
            defineField({ name: "value", title: "Value [Example: Next.js + Sanity]", type: "string", validation: (rule) => rule.required() }),
            defineField({ name: "hint", title: "Hint (Optional) [Example: Fast publishing workflow]", type: "string" }),
          ],
        },
      ],
    }),
    defineField({
      name: "results",
      title: "Results [Example: Qualified inquiries = +37%]",
      type: "array",
      description: "Business or product outcomes shown on the case study page.",
      group: "delivery",
      of: [
        {
          type: "object",
          fields: [
            defineField({ name: "label", title: "Label [Example: Qualified inquiries]", type: "string", validation: (rule) => rule.required() }),
            defineField({ name: "value", title: "Value [Example: +37%]", type: "string", validation: (rule) => rule.required() }),
            defineField({ name: "hint", title: "Hint (Optional) [Example: First 60 days]", type: "string" }),
          ],
        },
      ],
    }),
    defineField({
      name: "gallery",
      title: "Gallery [Example: 2-5 real supporting screenshots]",
      type: "array",
      description: "Additional screenshots from the live project.",
      group: "media",
      of: [
        {
          type: "image",
          options: { hotspot: true },
          fields: [defineField({ name: "alt", title: "Alt Text [Example: Service page section from the live website]", type: "string" })],
        },
      ],
    }),
  ],
  preview: {
    select: {
      title: "name",
      subtitle: "industry",
      categoryTitle: "category.title",
      media: "heroImage",
    },
    prepare: ({ title, subtitle, categoryTitle, media }) => ({
      title,
      subtitle: categoryTitle ?? subtitle,
      media,
    }),
  },
});
