import { defineField, defineType } from "sanity";

export const shopItemType = defineType({
  name: "shopItem",
  title: "Shop Item",
  type: "document",
  groups: [
    { name: "basics", title: "Basics" },
    { name: "commerce", title: "Commerce" },
    { name: "content", title: "Content" },
    { name: "variants", title: "Variants & Offers" },
    { name: "relations", title: "FAQ & Relations" },
    { name: "delivery", title: "Delivery" },
    { name: "media", title: "Media & Preview" },
  ],
  fields: [
    defineField({
      name: "name",
      title: "Name [Example: Three Circles - Interior Designer company website]",
      type: "string",
      description: "Product or template name exactly as you want it to appear on the shop card and slug page.",
      group: "basics",
      validation: (rule) => rule.required().min(3),
    }),
    defineField({
      name: "slug",
      title: "Slug [Example: three-circles-interior-designer-company-website]",
      type: "slug",
      options: { source: "name", maxLength: 96 },
      description: "Used in the product URL. Keep it lowercase and hyphen-separated.",
      group: "basics",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "price",
      title: "Price [Example: $999]",
      type: "string",
      description: "Display price shown on shop cards and the product detail page.",
      group: "commerce",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "livePreviewUrl",
      title: "Live Preview URL [Example: https://template-demo.vercel.app]",
      type: "url",
      description: "Paste the real public demo link users should open when they click Live Preview.",
      group: "media",
    }),
    defineField({
      name: "embeddedPreviewUrl",
      title: "Embeddable Preview URL (Optional)",
      type: "url",
      description: "Use only when the demo site allows iframe embedding.",
      group: "media",
    }),
    defineField({
      name: "category",
      title: "Category Reference (Optional) [Example: Templates]",
      type: "reference",
      to: [{ type: "shopCategory" }],
      description: "Optional linked category document. If empty, the fallback label below will still work.",
      group: "basics",
    }),
    defineField({
      name: "parentCategoryLabel",
      title: "Parent Category Label [Example: Business & Professional]",
      type: "string",
      description: "Top-level product family label used for taxonomy grouping.",
      group: "basics",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "parentCategorySlug",
      title: "Parent Category Slug [Example: business-professional]",
      type: "string",
      options: {
        list: [
          { title: "Business & Professional", value: "business-professional" },
          { title: "Email Templates", value: "email-templates" },
          { title: "Documents & Reports", value: "documents-reports" },
          { title: "E-Commerce & Marketing", value: "ecommerce-marketing" },
          { title: "Education & Info Products", value: "education-info-products" },
          { title: "Tools & Utilities", value: "tools-utilities" },
        ],
      },
      description: "Canonical top-level taxonomy key.",
      group: "basics",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "categoryLabel",
      title: "Category Label [Example: Interior Designer Company]",
      type: "string",
      description: "Visible category text shown to users.",
      group: "basics",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "categorySlug",
      title: "Category Slug [Example: interior-designer-company]",
      type: "string",
      options: {
        list: [
          { title: "HTML Templates", value: "html-templates" },
          { title: "HTML Business Profiles", value: "html-business-profiles" },
          { title: "SaaS Templates", value: "saas-templates" },
          { title: "AI & Automation", value: "ai-automation" },
          { title: "MCP Servers", value: "mcp-servers" },
          { title: "SEO Toolkits", value: "seo-toolkits" },
          { title: "Bundles", value: "bundles" },
          { title: "Free Products", value: "free-products" },
        ],
      },
      description: "Filter key for the shop page. Use lowercase with hyphens.",
      group: "basics",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "type",
      title: "Type [Example: SaaS]",
      type: "string",
      description: "Short product type shown beside category.",
      group: "basics",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "typeSlug",
      title: "Type Slug [Example: agency-landing-pages]",
      type: "string",
      options: {
        list: [
          { title: "Business Profile Pages", value: "business-profile-pages" },
          { title: "Digital Business Cards", value: "digital-business-cards" },
          { title: "Agency Landing Pages", value: "agency-landing-pages" },
          { title: "Restaurant Menu Pages", value: "restaurant-menu-pages" },
          { title: "Newsletter Templates", value: "newsletter-templates" },
          { title: "Transactional Email Templates", value: "transactional-email-templates" },
          { title: "Promotional Email Blasts", value: "promotional-email-blasts" },
          { title: "Cold Outreach Templates", value: "cold-outreach-templates" },
          { title: "HTML Invoice Templates", value: "html-invoice-templates" },
          { title: "Proposal Templates", value: "proposal-templates" },
          { title: "HTML Resumes / CV", value: "html-resumes-cv" },
          { title: "Annual Report Pages", value: "annual-report-pages" },
          { title: "Product Launch Pages", value: "product-launch-pages" },
          { title: "Link-in-Bio Pages", value: "link-in-bio-pages" },
          { title: "Affiliate Landing Pages", value: "affiliate-landing-pages" },
          { title: "App Promo Pages", value: "app-promo-pages" },
          { title: "Course Landing Pages", value: "course-landing-pages" },
          { title: "Lead Magnet Download Pages", value: "lead-magnet-download-pages" },
          { title: "Event / Webinar Pages", value: "event-webinar-pages" },
          { title: "Portfolio Templates", value: "portfolio-templates" },
          { title: "Calculators", value: "calculators" },
          { title: "Checklists & Trackers", value: "checklists-trackers" },
          { title: "FAQ / Knowledge Base Pages", value: "faq-knowledge-base-pages" },
          { title: "Coming Soon / Maintenance Pages", value: "coming-soon-maintenance-pages" },
        ],
      },
      description: "Canonical type slug used for /products/category/<type-slug> routes.",
      group: "basics",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "industry",
      title: "Industry [Example: Service]",
      type: "string",
      description: "Readable industry label shown in filters and meta table.",
      group: "basics",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "industrySlug",
      title: "Industry Slug [Example: service]",
      type: "string",
      description: "Filter key for industry.",
      group: "basics",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "tag",
      title: "Badge Tag (Optional) [Example: Best Seller]",
      type: "string",
      description: "Small badge shown on product cards.",
      group: "commerce",
    }),
    defineField({
      name: "published",
      title: "Published",
      type: "boolean",
      initialValue: true,
      description: "Turn off to hide this item from the public shop.",
      group: "commerce",
    }),
    defineField({
      name: "featuredRank",
      title: "Featured Rank [Example: 10]",
      type: "number",
      initialValue: 999,
      description: "Lower numbers appear earlier in CMS-driven shop ordering.",
      group: "commerce",
    }),
    defineField({
      name: "rating",
      title: "Rating (Optional) [Example: 4.9]",
      type: "number",
      description: "Decimal rating shown in product cards and detail page.",
      group: "commerce",
      validation: (rule) => rule.min(0).max(5),
    }),
    defineField({
      name: "reviewCount",
      title: "Review Count (Optional) [Example: 2.1K]",
      type: "string",
      description: "Readable count shown beside the rating.",
      group: "commerce",
    }),
    defineField({
      name: "salesCount",
      title: "Sales Count (Optional) [Example: 307]",
      type: "string",
      description: "Readable sales/social proof text.",
      group: "commerce",
    }),
    defineField({
      name: "teaser",
      title: "Teaser [Example: A ready interior design website with elegant sections and booking-ready pages.]",
      type: "string",
      description: "Short opening description shown near the top of the slug page.",
      group: "content",
      validation: (rule) => rule.required().min(6),
    }),
    defineField({
      name: "features",
      title: "Feature Descriptions [Example: Conversion-focused hero with trust proof and CTA logic]",
      type: "array",
      of: [{ type: "string" }],
      description: "Primary buyer-facing details list. Aim for 8-14 concrete, non-duplicative bullets (Envato-style depth) covering structure, conversion flow, CMS editing, responsive behavior, SEO/performance baseline, and launch readiness.",
      group: "content",
      validation: (rule) => rule.min(1),
    }),
    defineField({
      name: "variants",
      title: "Product Variants (Standard / Premium / Done-For-You)",
      type: "array",
      description: "Add purchasable tiers users can compare and select before checkout.",
      group: "variants",
      of: [
        {
          type: "object",
          fields: [
            defineField({
              name: "slug",
              title: "Variant Slug [Example: standard]",
              type: "string",
              validation: (rule) => rule.required(),
            }),
            defineField({
              name: "tierName",
              title: "Tier Name",
              type: "string",
              options: {
                list: [
                  { title: "Standard", value: "Standard" },
                  { title: "Premium", value: "Premium" },
                  { title: "Done-For-You", value: "Done-For-You" },
                ],
              },
              validation: (rule) => rule.required(),
            }),
            defineField({
              name: "title",
              title: "Package Title [Example: Standard Website Package]",
              type: "string",
              validation: (rule) => rule.required(),
            }),
            defineField({
              name: "price",
              title: "Package Price [Example: $999]",
              type: "string",
              validation: (rule) => rule.required(),
            }),
            defineField({
              name: "fulfillmentType",
              title: "Fulfillment Type",
              type: "string",
              options: {
                list: [
                  { title: "Digital Download", value: "digital_download" },
                  { title: "Hybrid Support", value: "hybrid_support" },
                  { title: "Done For You Service", value: "done_for_you_service" },
                ],
              },
              initialValue: "digital_download",
              validation: (rule) => rule.required(),
            }),
            defineField({
              name: "includes",
              title: "Includes",
              type: "array",
              of: [{ type: "string" }],
              validation: (rule) => rule.required().min(1),
            }),
            defineField({
              name: "comparisonPoints",
              title: "Comparison Points (Optional)",
              type: "array",
              of: [{ type: "string" }],
            }),
            defineField({
              name: "recommended",
              title: "Recommended Tier",
              type: "boolean",
              initialValue: false,
            }),
          ],
        },
      ],
    }),
    defineField({
      name: "customizationUpsells",
      title: "Customization Upsells",
      type: "array",
      description: "Optional Done-For-You or setup offers shown beside tier comparison.",
      group: "variants",
      of: [
        {
          type: "object",
          fields: [
            defineField({ name: "title", title: "Title", type: "string", validation: (rule) => rule.required() }),
            defineField({
              name: "description",
              title: "Description",
              type: "text",
              rows: 3,
              validation: (rule) => rule.required().min(12),
            }),
            defineField({
              name: "ctaLabel",
              title: "CTA Label [Example: Request Done-For-You Scope]",
              type: "string",
              validation: (rule) => rule.required(),
            }),
            defineField({
              name: "ctaHref",
              title: "CTA URL [Example: /contact?intent=done-for-you]",
              type: "string",
              validation: (rule) => rule.required(),
            }),
          ],
        },
      ],
    }),
    defineField({
      name: "summary",
      title: "Summary [Example: Best for studios that need a premium website fast without custom build delays.]",
      type: "text",
      rows: 4,
      description: "Fuller summary shown on product cards and the detail page.",
      group: "content",
      validation: (rule) => rule.required().min(20),
    }),
    defineField({
      name: "audience",
      title: "Ideal For [Example: Interior design studios, boutique agencies, luxury service brands]",
      type: "string",
      description: "Used in the Ideal for box on the product detail page.",
      group: "content",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "faqs",
      title: "Product FAQ",
      type: "array",
      description: "Common buyer objections and product-specific answers.",
      group: "relations",
      of: [
        {
          type: "object",
          fields: [
            defineField({ name: "question", title: "Question", type: "string", validation: (rule) => rule.required() }),
            defineField({
              name: "answer",
              title: "Answer",
              type: "text",
              rows: 3,
              validation: (rule) => rule.required(),
            }),
          ],
        },
      ],
    }),
    defineField({
      name: "relatedProductSlugs",
      title: "Related Product Slugs",
      type: "array",
      description: "Product slugs to show as related cards near the bottom of the detail page.",
      group: "relations",
      of: [{ type: "string" }],
      validation: (rule) => rule.max(6),
    }),
    defineField({
      name: "relatedServiceSlugs",
      title: "Related Service Slugs",
      type: "array",
      description: "Service slugs used for cross-sell links (for example: websites, saas-applications).",
      group: "relations",
      of: [{ type: "string" }],
      validation: (rule) => rule.max(6),
    }),
    defineField({
      name: "previewVariant",
      title: "Fallback Preview Style [Example: marketing]",
      type: "string",
      options: {
        list: [
          { title: "Marketing", value: "marketing" },
          { title: "MCP", value: "mcp" },
          { title: "Dashboard", value: "dashboard" },
          { title: "Automation", value: "automation" },
          { title: "Mobile", value: "mobile" },
          { title: "Booking", value: "booking" },
        ],
      },
      initialValue: "marketing",
      description: "Used only if no real uploaded product image is available.",
      group: "media",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "includes",
      title: "What Is Included [Example: Homepage, About page, Contact page, CMS setup guide]",
      type: "array",
      of: [{ type: "string" }],
      description: "One deliverable or included item per line.",
      group: "delivery",
      validation: (rule) => rule.required().min(1),
    }),
    defineField({
      name: "inScope",
      title: "In Scope [Example: Template setup, CMS wiring, and launch-ready baseline configuration]",
      type: "array",
      of: [{ type: "string" }],
      description: "Explicitly list what is included within the template price.",
      group: "delivery",
      validation: (rule) => rule.min(1),
    }),
    defineField({
      name: "outOfScope",
      title: "Out of Scope [Example: New feature modules, advanced automation, or major custom redesign]",
      type: "array",
      of: [{ type: "string" }],
      description: "Explicitly list what is not included in the listed template price.",
      group: "delivery",
      validation: (rule) => rule.min(1),
    }),
    defineField({
      name: "enhancementPlan",
      title: "Enhancement / Scaling Plan [Example: CRM automation, additional pages, conversion experiments]",
      type: "array",
      of: [{ type: "string" }],
      description: "Optional roadmap ideas for buyers who want to scale after purchase.",
      group: "delivery",
      validation: (rule) => rule.min(1),
    }),
    defineField({
      name: "stack",
      title: "Stack / Tools Used [Example: Next.js, Tailwind CSS, Sanity, Stripe]",
      type: "array",
      of: [{ type: "string" }],
      description: "Technology names or platform tools used in the template/product.",
      group: "delivery",
      validation: (rule) => rule.required().min(1),
    }),
    defineField({
      name: "highlights",
      title: "Highlights [Example: Pages = 12, Setup time = 2 hrs]",
      type: "array",
      description: "Small key-value facts shown in the At a glance section.",
      group: "delivery",
      of: [
        {
          type: "object",
          fields: [
            defineField({ name: "label", title: "Label [Example: Pages]", type: "string", validation: (rule) => rule.required() }),
            defineField({ name: "value", title: "Value [Example: 12]", type: "string", validation: (rule) => rule.required() }),
          ],
        },
      ],
    }),
    defineField({
      name: "mainImage",
      title: "Main Product Image [Example: upload the real homepage or template screenshot]",
      type: "image",
      options: { hotspot: true },
      description: "Optional and manual only. Upload this in Studio when you have the final screenshot.",
      group: "media",
      fields: [
        defineField({ name: "alt", title: "Alt Text [Example: Homepage screenshot of the Three Circles interior design template]", type: "string" }),
      ],
    }),
    defineField({
      name: "mainImageAlt",
      title: "Main Image Alt Fallback [Example: Premium interior design template preview]",
      type: "string",
      description: "Used if you do not set alt text directly inside the uploaded image field.",
      group: "media",
    }),
    defineField({
      name: "gallery",
      title: "Gallery [Example: 2-5 additional real screenshots]",
      type: "array",
      description: "Additional screenshots for the shop slug page preview gallery.",
      group: "media",
      of: [
        {
          type: "image",
          options: { hotspot: true },
          fields: [defineField({ name: "alt", title: "Alt Text [Example: Contact section screenshot from the live template]", type: "string" })],
        },
      ],
    }),
  ],
  preview: {
    select: {
      title: "name",
      subtitle: "price",
      media: "mainImage",
    },
  },
});
