import { defineField, defineType } from "sanity";

export const shopItemType = defineType({
  name: "shopItem",
  title: "Shop Item",
  type: "document",
  groups: [
    { name: "basics", title: "Basics" },
    { name: "commerce", title: "Commerce" },
    { name: "content", title: "Content" },
    { name: "delivery", title: "Delivery" },
    { name: "media", title: "Media & Preview" },
  ],
  fields: [
    defineField({
      name: "name",
      title: "Name [Example: Three Circles - Interior Designer company website]",
      type: "string",
      description: "Product or template name exactly as you want it to appear on the shop card and slug page.",
      group: "basics",
      validation: (rule) => rule.required().min(3),
    }),
    defineField({
      name: "slug",
      title: "Slug [Example: three-circles-interior-designer-company-website]",
      type: "slug",
      options: { source: "name", maxLength: 96 },
      description: "Used in the product URL. Keep it lowercase and hyphen-separated.",
      group: "basics",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "price",
      title: "Price [Example: $999]",
      type: "string",
      description: "Display price shown on shop cards and the product detail page.",
      group: "commerce",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "livePreviewUrl",
      title: "Live Preview URL [Example: https://template-demo.vercel.app]",
      type: "url",
      description: "Paste the real public demo link users should open when they click Live Preview.",
      group: "media",
    }),
    defineField({
      name: "embeddedPreviewUrl",
      title: "Embeddable Preview URL (Optional)",
      type: "url",
      description: "Use only when the demo site allows iframe embedding.",
      group: "media",
    }),
    defineField({
      name: "category",
      title: "Category Reference (Optional) [Example: Templates]",
      type: "reference",
      to: [{ type: "shopCategory" }],
      description: "Optional linked category document. If empty, the fallback label below will still work.",
      group: "basics",
    }),
    defineField({
      name: "categoryLabel",
      title: "Category Label [Example: Interior Designer Company]",
      type: "string",
      description: "Visible category text shown to users.",
      group: "basics",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "categorySlug",
      title: "Category Slug [Example: interior-designer-company]",
      type: "string",
      description: "Filter key for the shop page. Use lowercase with hyphens.",
      group: "basics",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "type",
      title: "Type [Example: SaaS]",
      type: "string",
      description: "Short product type shown beside category.",
      group: "basics",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "typeSlug",
      title: "Type Slug [Example: saas]",
      type: "string",
      description: "Filter key for product type.",
      group: "basics",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "industry",
      title: "Industry [Example: Service]",
      type: "string",
      description: "Readable industry label shown in filters and meta table.",
      group: "basics",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "industrySlug",
      title: "Industry Slug [Example: service]",
      type: "string",
      description: "Filter key for industry.",
      group: "basics",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "tag",
      title: "Badge Tag (Optional) [Example: Best Seller]",
      type: "string",
      description: "Small badge shown on product cards.",
      group: "commerce",
    }),
    defineField({
      name: "published",
      title: "Published",
      type: "boolean",
      initialValue: true,
      description: "Turn off to hide this item from the public shop.",
      group: "commerce",
    }),
    defineField({
      name: "featuredRank",
      title: "Featured Rank [Example: 10]",
      type: "number",
      initialValue: 999,
      description: "Lower numbers appear earlier in CMS-driven shop ordering.",
      group: "commerce",
    }),
    defineField({
      name: "rating",
      title: "Rating (Optional) [Example: 4.9]",
      type: "number",
      description: "Decimal rating shown in product cards and detail page.",
      group: "commerce",
      validation: (rule) => rule.min(0).max(5),
    }),
    defineField({
      name: "reviewCount",
      title: "Review Count (Optional) [Example: 2.1K]",
      type: "string",
      description: "Readable count shown beside the rating.",
      group: "commerce",
    }),
    defineField({
      name: "salesCount",
      title: "Sales Count (Optional) [Example: 307]",
      type: "string",
      description: "Readable sales/social proof text.",
      group: "commerce",
    }),
    defineField({
      name: "teaser",
      title: "Teaser [Example: A ready interior design website with elegant sections and booking-ready pages.]",
      type: "string",
      description: "Short opening description shown near the top of the slug page.",
      group: "content",
      validation: (rule) => rule.required().min(6),
    }),
    defineField({
      name: "summary",
      title: "Summary [Example: Best for studios that need a premium website fast without custom build delays.]",
      type: "text",
      rows: 4,
      description: "Fuller summary shown on product cards and the detail page.",
      group: "content",
      validation: (rule) => rule.required().min(20),
    }),
    defineField({
      name: "audience",
      title: "Ideal For [Example: Interior design studios, boutique agencies, luxury service brands]",
      type: "string",
      description: "Used in the Ideal for box on the product detail page.",
      group: "content",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "previewVariant",
      title: "Fallback Preview Style [Example: marketing]",
      type: "string",
      options: {
        list: [
          { title: "Marketing", value: "marketing" },
          { title: "MCP", value: "mcp" },
          { title: "Dashboard", value: "dashboard" },
          { title: "Automation", value: "automation" },
          { title: "Mobile", value: "mobile" },
          { title: "Booking", value: "booking" },
        ],
      },
      initialValue: "marketing",
      description: "Used only if no real uploaded product image is available.",
      group: "media",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "includes",
      title: "What Is Included [Example: Homepage, About page, Contact page, CMS setup guide]",
      type: "array",
      of: [{ type: "string" }],
      description: "One deliverable or included item per line.",
      group: "delivery",
      validation: (rule) => rule.required().min(1),
    }),
    defineField({
      name: "stack",
      title: "Stack / Tools Used [Example: Next.js, Tailwind CSS, Sanity, Stripe]",
      type: "array",
      of: [{ type: "string" }],
      description: "Technology names or platform tools used in the template/product.",
      group: "delivery",
      validation: (rule) => rule.required().min(1),
    }),
    defineField({
      name: "highlights",
      title: "Highlights [Example: Pages = 12, Setup time = 2 hrs]",
      type: "array",
      description: "Small key-value facts shown in the At a glance section.",
      group: "delivery",
      of: [
        {
          type: "object",
          fields: [
            defineField({ name: "label", title: "Label [Example: Pages]", type: "string", validation: (rule) => rule.required() }),
            defineField({ name: "value", title: "Value [Example: 12]", type: "string", validation: (rule) => rule.required() }),
          ],
        },
      ],
    }),
    defineField({
      name: "mainImage",
      title: "Main Product Image [Example: upload the real homepage or template screenshot]",
      type: "image",
      options: { hotspot: true },
      description: "This image will be shown on shop cards and on the product slug page instead of the fake preview mockup.",
      group: "media",
      fields: [
        defineField({ name: "alt", title: "Alt Text [Example: Homepage screenshot of the Three Circles interior design template]", type: "string" }),
      ],
    }),
    defineField({
      name: "mainImageAlt",
      title: "Main Image Alt Fallback [Example: Premium interior design template preview]",
      type: "string",
      description: "Used if you do not set alt text directly inside the uploaded image field.",
      group: "media",
    }),
  ],
  preview: {
    select: {
      title: "name",
      subtitle: "price",
      media: "mainImage",
    },
  },
});
